import os
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'src', 'pages', 'OutgoingLetters.jsx')

# Build file content without backticks to avoid Python string issues
# Badge class uses string concatenation instead of template literals
c = ""
c += "import { useState, useRef } from 'react';\n"
c += "import { Plus, Search, Eye, Edit2, Trash2, Upload, X, Paperclip, Download } from 'lucide-react';\n"
c += "import { useApp } from '../context/AppContext';\n"
c += "import { departments, dispatchMethods, outgoingStatuses } from '../data/mockData';\n"
c += "\n"
c += "const SC = { { recipient:'', recipientOrg:'', subject:'', department:'', datePrepared:'', relatedIncoming:'', dispatchMethod:'Email', trackingNo:'', responsibleOfficer:'', status:'Draft', attachment:null };",
"",
"const ALLOWED = ['application/pdf','image/jpeg','image/png','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'];",
"",
"function fmt(b){ return !b?'':b<1048576?(b/1024).toFixed(1)+' KB':(b/1048576).toFixed(1)+' MB'; }",
"",
"function FileUploadZone({ value, onChange }) {",
"  const inputRef = useRef();",
"  const [dragging, setDragging] = useState(false);",
"  const [fileError, setFileError] = useState('');",
"",
"  const process = (file) => {",
"    setFileError('');",
"    if (!ALLOWED.includes(file.type)) { setFileError('Only PDF, JPG, PNG, DOC, DOCX allowed.'); return; }",
"    if (file.size > 10*1024*1024) { setFileError('File must be under 10 MB.'); return; }",
"    const reader = new FileReader();",
"    reader.onload = (e) => onChange({ name:file.name, size:file.size, type:file.type, dataUrl:e.target.result });",
"    reader.readAsDataURL(file);",
"  };",
"",
"  if (value) return (",
"    <div style={{ display:'flex', alignItems:'center', gap:12, padding:'12px 16px', border:'1.5px solid var(--border)', borderRadius:8, background:'var(--surface-2)' }}>",
"      <Paperclip size={18} color='#6366f1' />",
"      <div style={{ flex:1, minWidth:0 }}>",
"        <div style={{ fontSize:13, fontWeight:600, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }}>{value.name}</div>",
"        <div style={{ fontSize:11, color:'var(--text-faint)' }}>{fmt(value.size)}</div>",
"      </div>",
"      <a href={value.dataUrl} target='_blank' rel='noreferrer' style={{ fontSize:12, color:'#6366f1', fontWeight:600, textDecoration:'none' }}>Preview</a>",
"      <button type='button' onClick={() => onChange(null)} style={{ background:'none', border:'none', cursor:'pointer', color:'#ef4444', padding:4 }}><X size={14} /></button>",
"    </div>",
"  );",
"",
"  return (",
"    <div>",
"      <div",
"        onClick={() => inputRef.current.click()}",
"        onDragOver={e => { e.preventDefault(); setDragging(true); }}",
"        onDragLeave={() => setDragging(false)}",
"        onDrop={e => { e.preventDefault(); setDragging(false); const f=e.dataTransfer.files[0]; if(f) process(f); }}",
"        style={{ border:`2px dashed ${dragging?'#6366f1':'var(--border)'}`, borderRadius:8, padding:'28px 20px', textAlign:'center', cursor:'pointer', background:dragging?'rgba(99,102,241,.05)':'var(--surface-2)', transition:'all .15s' }}",
"      >",
"        <Upload size={24} style={{ margin:'0 auto 10px', display:'block', color:dragging?'#6366f1':'var(--text-faint)' }} />",
"        <div style={{ fontSize:13, fontWeight:600, color:'var(--text)' }}>{dragging?'Drop file here':'Click to upload or drag & drop'}</div>",
"        <div style={{ fontSize:11, color:'var(--text-faint)', marginTop:4 }}>PDF, JPG, PNG, DOC, DOCX — max 10 MB</div>",
"      </div>",
"      <input ref={inputRef} type='file' accept='.pdf,.jpg,.jpeg,.png,.doc,.docx' style={{ display:'none' }}",
"        onChange={e => { if(e.target.files[0]) process(e.target.files[0]); e.target.value=''; }} />",
"      {fileError && <div style={{ fontSize:12, color:'#ef4444', marginTop:6 }}>{fileError}</div>}",
"    </div>",
"  );",
"}",
"",
"export default function OutgoingLetters() {",
"  const { outgoing, addOutgoing, updateOutgoing, deleteOutgoing, readOnly } = useApp();",
"  const [search, setSearch] = useState('');",
"  const [filterStatus, setFilterStatus] = useState('');",
"  const [showModal, setShowModal] = useState(false);",
"  const [viewLetter, setViewLetter] = useState(null);",
"  const [editLetter, setEditLetter] = useState(null);",
"  const [form, setForm] = useState(emptyForm);",
"",
"  const filtered = outgoing.filter(l => {",
"    const q = search.toLowerCase();",
"    return (!q || l.refNo?.toLowerCase().includes(q) || l.recipient?.toLowerCase().includes(q) || l.subject?.toLowerCase().includes(q))",
"      && (!filterStatus || l.status === filterStatus);",
"  });",
"",
"  const openAdd = () => { setForm(emptyForm); setEditLetter(null); setShowModal(true); };",
"  const openEdit = (l) => { setForm({...l, attachment:l.attachment||null}); setEditLetter(l); setShowModal(true); };",
"  const handleSubmit = (e) => { e.preventDefault(); if(editLetter) updateOutgoing(editLetter.id,form); else addOutgoing(form); setShowModal(false); };",
"  const handleDelete = (id) => { if(window.confirm('Delete this letter?')) deleteOutgoing(id); };",
"  const f = (k,v) => setForm(p=>({...p,[k]:v}));",
"",
"  return (",
"    <div>",
"      <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:20, flexWrap:'wrap', gap:12 }}>",
"        <div>",
"          <h1 style={{ fontSize:22, fontWeight:700 }}>Outgoing Letters</h1>",
"          <p style={{ color:'var(--text-muted)', fontSize:13 }}>{outgoing.length} total letters registered</p>",
"        </div>",
"        {!readOnly && <button className='btn btn-primary' onClick={openAdd}><Plus size={16} /> Register Letter</button>}",
"      </div>",
"",
"      <div className='card' style={{ marginBottom:16 }}>",
"        <div style={{ padding:'14px 20px', display:'flex', gap:12, flexWrap:'wrap', alignItems:'center' }}>",
"          <div style={{ position:'relative', flex:1, minWidth:200 }}>",
"            <Search size={15} style={{ position:'absolute', left:10, top:'50%', transform:'translateY(-50%)', color:'var(--text-faint)' }} />",
"            <input className='form-control' placeholder='Search ref, recipient, subject...' value={search} onChange={e=>setSearch(e.target.value)} style={{ paddingLeft:32 }} />",
"          </div>",
"          <select className='form-control' style={{ width:160 }} value={filterStatus} onChange={e=>setFilterStatus(e.target.value)}>",
"            <option value=''>All Statuses</option>",
"            {outgoingStatuses.map(s=><option key={s}>{s}</option>)}",
"          </select>",
"          {(search||filterStatus) && <button className='btn btn-ghost btn-sm' onClick={()=>{setSearch('');setFilterStatus('');}}><X size={14}/> Clear</button>}",
"        </div>",
"      </div>",
"",
"      <div className='card'>",
"        <div className='table-wrap'>",
"          <table>",
"            <thead><tr>",
"              <th>Ref No.</th><th>Date</th><th>Recipient</th><th>Organization</th>",
"              <th>Subject</th><th>Dept</th><th>Dispatch</th><th>Officer</th><th>File</th><th>Status</th><th>Actions</th>",
"            </tr></thead>",
"            <tbody>",
"              {filtered.length===0",
"                ? <tr><td colSpan={11} style={{ textAlign:'center', padding:40, color:'var(--text-faint)' }}>No letters found</td></tr>",
"                : filtered.map(l=>(",
"                  <tr key={l.id}>",
"                    <td style={{ fontWeight:600, color:'#0891b2' }}>{l.refNo}</td>",
"                    <td>{l.datePrepared}</td>",
"                    <td>{l.recipient}</td>",
"                    <td style={{ color:'var(--text-muted)' }}>{l.recipientOrg}</td>",
"                    <td style={{ maxWidth:160, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }}>{l.subject}</td>",
"                    <td>{l.department}</td>",
"                    <td>{l.dispatchMethod}</td>",
"                    <td>{l.responsibleOfficer}</td>",
"                    <td>{l.attachment",
"                      ? <a href={l.attachment.dataUrl} target='_blank' rel='noreferrer' title={l.attachment.name} style={{ display:'flex', alignItems:'center', gap:4, color:'#6366f1', fontSize:12, textDecoration:'none' }}>",
"                          <Paperclip size={13}/>{l.attachment.name.length>12?l.attachment.name.slice(0,12)+'...':l.attachment.name}",
"                        </a>",
"                      : <span style={{ color:'var(--text-faint)', fontSize:12 }}>-</span>}",
"                    </td>",
"                    <td><span className={`badge ${statusColor[l.status]||'badge-gray'}`}>{l.status}</span></td>",
"                    <td><div style={{ display:'flex', gap:4 }}>",
"                      <button className='btn btn-ghost btn-icon btn-sm' title='View' onClick={()=>setViewLetter(l)}><Eye size={14}/></button>",
"                      {!readOnly && <>",
"                        <button className='btn btn-ghost btn-icon btn-sm' title='Edit' onClick={()=>openEdit(l)}><Edit2 size={14}/></button>",
"                        <button className='btn btn-ghost btn-icon btn-sm' title='Delete' onClick={()=>handleDelete(l.id)} style={{ color:'#ef4444' }}><Trash2 size={14}/></button>",
"                      </>}",
"                    </div></td>",
"                  </tr>",
"                ))}",
"            </tbody>",
"          </table>",
"        </div>",
"        <div style={{ padding:'12px 20px', borderTop:'1px solid var(--border)', color:'var(--text-faint)', fontSize:12 }}>",
"          Showing {filtered.length} of {outgoing.length} letters",
"        </div>",
"      </div>",
"",
"      {showModal && (",
"        <div className='modal-overlay' onClick={e=>e.target===e.currentTarget&&setShowModal(false)}>",
"          <div className='modal modal-lg'>",
"            <div className='modal-header'>",
"              <h2 style={{ fontSize:17, fontWeight:700 }}>{editLetter?'Edit Outgoing Letter':'Register Outgoing Letter'}</h2>",
"              <button className='btn btn-ghost btn-icon' onClick={()=>setShowModal(false)}><X size={18}/></button>",
"            </div>",
"            <form onSubmit={handleSubmit}>",
"              <div className='modal-body'>",
"                <div className='grid grid-2' style={{ gap:16 }}>",
"                  <div className='form-group'><label className='form-label'>Recipient Name *</label>",
"                    <input className='form-control' required value={form.recipient} onChange={e=>f('recipient',e.target.value)} placeholder='Full name' /></div>",
"                  <div className='form-group'><label className='form-label'>Recipient Organization *</label>",
"                    <input className='form-control' required value={form.recipientOrg} onChange={e=>f('recipientOrg',e.target.value)} placeholder='Organization name' /></div>",
"                  <div className='form-group' style={{ gridColumn:'1/-1' }}><label className='form-label'>Subject *</label>",
"                    <input className='form-control' required value={form.subject} onChange={e=>f('subject',e.target.value)} placeholder='Letter subject' /></div>",
"                  <div className='form-group'><label className='form-label'>Department *</label>",
"                    <select className='form-control' required value={form.department} onChange={e=>f('department',e.target.value)}>",
"                      <option value=''>Select department</option>",
"                      {departments.map(d=><option key={d}>{d}</option>)}",
"                    </select></div>",
"                  <div className='form-group'><label className='form-label'>Date Prepared *</label>",
"                    <input type='date' className='form-control' required value={form.datePrepared} onChange={e=>f('datePrepared',e.target.value)} /></div>",
"                  <div className='form-group'><label className='form-label'>Related Incoming Ref</label>",
"                    <input className='form-control' value={form.relatedIncoming} onChange={e=>f('relatedIncoming',e.target.value)} placeholder='e.g. INC-2026-001' /></div>",
"                  <div className='form-group'><label className='form-label'>Dispatch Method</label>",
"                    <select className='form-control' value={form.dispatchMethod} onChange={e=>f('dispatchMethod',e.target.value)}>",
"                      {dispatchMethods.map(m=><option key={m}>{m}</option>)}",
"                    </select></div>",
"                  <div className='form-group'><label className='form-label'>Tracking Number</label>",
"                    <input className='form-control' value={form.trackingNo} onChange={e=>f('trackingNo',e.target.value)} placeholder='Courier tracking no.' /></div>",
"                  <div className='form-group'><label className='form-label'>Responsible Officer *</label>",
"                    <input className='form-control' required value={form.responsibleOfficer} onChange={e=>f('responsibleOfficer',e.target.value)} placeholder='Officer name' /></div>",
"                  <div className='form-group'><label className='form-label'>Status</label>",
"                    <select className='form-control' value={form.status} onChange={e=>f('status',e.target.value)}>",
"                      {outgoingStatuses.map(s=><option key={s}>{s}</option>)}",
"                    </select></div>",
"                  <div className='form-group' style={{ gridColumn:'1/-1' }}>",
"                    <label className='form-label'>Upload Signed / Hardcopy Document</label>",
"                    <FileUploadZone value={form.attachment} onChange={att=>f('attachment',att)} />",
"                  </div>",
"                </div>",
"              </div>",
"              <div className='modal-footer'>",
"                <button type='button' className='btn btn-ghost' onClick={()=>setShowModal(false)}>Cancel</button>",
"                <button type='submit' className='btn btn-primary'>{editLetter?'Save Changes':'Register Letter'}</button>",
"              </div>",
"            </form>",
"          </div>",
"        </div>",
"      )}",
"",
"      {viewLetter && (",
"        <div className='modal-overlay' onClick={e=>e.target===e.currentTarget&&setViewLetter(null)}>",
"          <div className='modal'>",
"            <div className='modal-header'>",
"              <div><h2 style={{ fontSize:17, fontWeight:700 }}>{viewLetter.refNo}</h2>",
"                <p style={{ fontSize:12, color:'var(--text-muted)', marginTop:2 }}>Outgoing Letter Details</p></div>",
"              <button className='btn btn-ghost btn-icon' onClick={()=>setViewLetter(null)}><X size={18}/></button>",
"            </div>",
"            <div className='modal-body'>",
"              <div className='grid grid-2' style={{ gap:16 }}>",
"                {[['Reference No.',viewLetter.refNo],['Date Prepared',viewLetter.datePrepared],",
"                  ['Recipient',viewLetter.recipient],['Organization',viewLetter.recipientOrg],",
"                  ['Department',viewLetter.department],['Dispatch Method',viewLetter.dispatchMethod],",
"                  ['Responsible Officer',viewLetter.responsibleOfficer],",
"                  ['Tracking No.',viewLetter.trackingNo||'-'],['Related Incoming',viewLetter.relatedIncoming||'-'],",
"                ].map(([k,v])=>(",
"                  <div key={k}>",
"                    <div style={{ fontSize:11, color:'var(--text-faint)', textTransform:'uppercase', letterSpacing:'.5px', marginBottom:4 }}>{k}</div>",
"                    <div style={{ fontSize:14, fontWeight:500 }}>{v}</div>",
"                  </div>",
"                ))}",
"                <div style={{ gridColumn:'1/-1' }}>",
"                  <div style={{ fontSize:11, color:'var(--text-faint)', textTransform:'uppercase', letterSpacing:'.5px', marginBottom:4 }}>Subject</div>",
"                  <div style={{ fontSize:14, fontWeight:500 }}>{viewLetter.subject}</div>",
"                </div>",
"                <div>",
"                  <div style={{ fontSize:11, color:'var(--text-faint)', textTransform:'uppercase', letterSpacing:'.5px', marginBottom:6 }}>Status</div>",
"                  <span className={`badge ${statusColor[viewLetter.status]||'badge-gray'}`}>{viewLetter.status}</span>",
"                </div>",
"                {viewLetter.attachment && (",
"                  <div style={{ gridColumn:'1/-1' }}>",
"                    <div style={{ fontSize:11, color:'var(--text-faint)', textTransform:'uppercase', letterSpacing:'.5px', marginBottom:8 }}>Attached Document</div>",
"                    <div style={{ display:'flex', alignItems:'center', gap:12, padding:'12px 16px', border:'1.5px solid var(--border)', borderRadius:8, background:'var(--surface-2)' }}>",
"                      <Paperclip size={18} color='#6366f1' />",
"                      <div style={{ flex:1 }}>",
"                        <div style={{ fontSize:13, fontWeight:600 }}>{viewLetter.attachment.name}</div>",
"                        <div style={{ fontSize:11, color:'var(--text-faint)' }}>{fmt(viewLetter.attachment.size)}</div>",
"                      </div>",
"                      <a href={viewLetter.attachment.dataUrl} download={viewLetter.attachment.name}",
"                        className='btn btn-outline btn-sm' style={{ textDecoration:'none', display:'flex', alignItems:'center', gap:6 }}>",
"                        <Download size={13}/> Download",
"                      </a>",
"                      <a href={viewLetter.attachment.dataUrl} target='_blank' rel='noreferrer'",
"                        className='btn btn-ghost btn-sm' style={{ textDecoration:'none' }}>View</a>",
"                    </div>",
"                  </div>",
"                )}",
"              </div>",
"            </div>",
"            <div className='modal-footer'>",
"              {!readOnly && <button className='btn btn-outline' onClick={()=>{setViewLetter(null);openEdit(viewLetter);}}><Edit2 size={14}/> Edit</button>}",
"              <button className='btn btn-ghost' onClick={()=>setViewLetter(null)}>Close</button>",
"            </div>",
"          </div>",
"        </div>",
"      )}",
"    </div>",
"  );",
"}",
]

with open(path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')

print('OK - wrote', len(lines), 'lines to', path)
